[21:26:53] üì¶ Processed dependencies!
cat: [2025-08-14 21:26:54.294594] /mount/admin/install_path: No such file or directory

2025-08-14 21:27:06.745 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:31:49.274 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

[21:31:49] ‚ùóÔ∏è
2025-08-14 21:31:49.614 503 GET /script-health-check (127.0.0.1) 342.92ms

2025-08-14 21:31:54.261 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:31:54.582 503 GET /script-health-check (127.0.0.1) 323.89ms

2025-08-14 21:31:59.264 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:31:59.509 503 GET /script-health-check (127.0.0.1) 247.83ms

2025-08-14 21:32:04.335 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:04.607 503 GET /script-health-check (127.0.0.1) 273.83ms

2025-08-14 21:32:09.282 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:09.563 503 GET /script-health-check (127.0.0.1) 283.56ms

2025-08-14 21:32:14.282 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:14.604 503 GET /script-health-check (127.0.0.1) 324.05ms

2025-08-14 21:32:19.280 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:19.575 503 GET /script-health-check (127.0.0.1) 296.17ms

2025-08-14 21:32:24.264 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:24.579 503 GET /script-health-check (127.0.0.1) 317.35ms

2025-08-14 21:32:29.291 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:29.628 503 GET /script-health-check (127.0.0.1) 339.21ms

2025-08-14 21:32:34.293 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:34.547 503 GET /script-health-check (127.0.0.1) 255.66ms

2025-08-14 21:32:39.294 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:39.651 503 GET /script-health-check (127.0.0.1) 358.54ms

2025-08-14 21:32:44.293 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:44.631 503 GET /script-health-check (127.0.0.1) 340.34ms

2025-08-14 21:32:49.288 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:49.613 503 GET /script-health-check (127.0.0.1) 326.83ms

2025-08-14 21:32:54.270 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:54.578 503 GET /script-health-check (127.0.0.1) 309.98ms

2025-08-14 21:32:59.294 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:32:59.611 503 GET /script-health-check (127.0.0.1) 319.01ms

2025-08-14 21:33:04.332 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:04.631 503 GET /script-health-check (127.0.0.1) 301.21ms

2025-08-14 21:33:09.303 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:09.585 503 GET /script-health-check (127.0.0.1) 284.49ms

2025-08-14 21:33:14.291 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:14.610 503 GET /script-health-check (127.0.0.1) 321.29ms

2025-08-14 21:33:19.303 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:19.634 503 GET /script-health-check (127.0.0.1) 333.15ms

2025-08-14 21:33:24.285 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:24.538 503 GET /script-health-check (127.0.0.1) 255.30ms

2025-08-14 21:33:29.292 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:29.638 503 GET /script-health-check (127.0.0.1) 347.97ms

2025-08-14 21:33:34.286 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:34.647 503 GET /script-health-check (127.0.0.1) 364.08ms

2025-08-14 21:33:39.283 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:39.623 503 GET /script-health-check (127.0.0.1) 340.89ms

2025-08-14 21:33:44.248 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:44.525 503 GET /script-health-check (127.0.0.1) 279.25ms

2025-08-14 21:33:49.272 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:49.595 503 GET /script-health-check (127.0.0.1) 325.08ms

2025-08-14 21:33:54.275 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:54.543 503 GET /script-health-check (127.0.0.1) 270.27ms

2025-08-14 21:33:59.319 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:33:59.657 503 GET /script-health-check (127.0.0.1) 340.72ms

2025-08-14 21:34:04.284 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:04.624 503 GET /script-health-check (127.0.0.1) 341.93ms

2025-08-14 21:34:09.364 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:09.675 503 GET /script-health-check (127.0.0.1) 312.94ms

2025-08-14 21:34:14.320 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:14.595 503 GET /script-health-check (127.0.0.1) 276.92ms

2025-08-14 21:34:19.300 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:19.661 503 GET /script-health-check (127.0.0.1) 363.11ms

2025-08-14 21:34:24.323 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:24.594 503 GET /script-health-check (127.0.0.1) 273.09ms

2025-08-14 21:34:29.341 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:29.672 503 GET /script-health-check (127.0.0.1) 332.80ms

2025-08-14 21:34:34.291 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:34.599 503 GET /script-health-check (127.0.0.1) 309.65ms

2025-08-14 21:34:39.266 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:39.573 503 GET /script-health-check (127.0.0.1) 309.87ms

2025-08-14 21:34:44.273 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:44.563 503 GET /script-health-check (127.0.0.1) 293.00ms

2025-08-14 21:34:49.257 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/mi_primer_repositorio/app_py.py", line 11, in <module>
    from sklearn.datasets import fetch_california_housing
ModuleNotFoundError: No module named 'sklearn'

2025-08-14 21:34:49.508 503 GET /script-health-check (127.0.0.1) 253.52ms

main
ferluqs-alt/mi_primer_repositorio/main/app_py.py
scikit-learn